/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module slowCount_5 (
    input clk,
    input rst,
    output reg [2:0] value
  );
  
  
  
  reg [24:0] M_flip_d, M_flip_q = 1'h0;
  
  wire [8-1:0] M_ctr_value;
  reg [1-1:0] M_ctr_clk;
  counter_11 ctr (
    .rst(rst),
    .clk(M_ctr_clk),
    .value(M_ctr_value)
  );
  
  always @* begin
    M_flip_d = M_flip_q;
    
    M_ctr_clk = M_flip_q[24+0-:1];
    M_flip_d = M_flip_q + 1'h1;
    value = M_ctr_value;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_flip_q <= 1'h0;
    end else begin
      M_flip_q <= M_flip_d;
    end
  end
  
endmodule
