/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 3
*/
module multi_dec_ctr_4 (
    input clk,
    input rst,
    input inc,
    output reg [8:0] digits
  );
  
  localparam DIGITS = 2'h3;
  
  
  wire [(2'h3+0)-1:0] M_dctr_ovf;
  wire [(2'h3+0)*3-1:0] M_dctr_value;
  reg [(2'h3+0)-1:0] M_dctr_inc;
  
  genvar GEN_dctr0;
  generate
  for (GEN_dctr0=0;GEN_dctr0<2'h3;GEN_dctr0=GEN_dctr0+1) begin: dctr_gen_0
    decimal_counter_10 dctr (
      .clk(clk),
      .rst(rst),
      .inc(M_dctr_inc[GEN_dctr0*(1)+(1)-1-:(1)]),
      .ovf(M_dctr_ovf[GEN_dctr0*(1)+(1)-1-:(1)]),
      .value(M_dctr_value[GEN_dctr0*(2'h3)+(2'h3)-1-:(2'h3)])
    );
  end
  endgenerate
  
  always @* begin
    M_dctr_inc[0+0-:1] = inc;
    digits = M_dctr_value;
    M_dctr_inc[1+1-:2] = M_dctr_ovf[0+1-:2];
  end
endmodule
